services:
  # PostgreSQL
  postgres:
    image: postgres:17
    container_name: postgres-db
    ports:
      - 5435:5434 
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME} 
      - POSTGRES_USER=${DB_USER} 
      - POSTGRES_PASSWORD=${DB_PASS} 
    networks:
      - api-postgres
    volumes:
      - postgres_local_data:/var/lib/postgresql/data:Z 

  # Go API
  logistic-service:
    container_name: logistic-service
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      - DB_STRING=${DB_STRING}
      - DB_CONTEXT=${DB_CONTEXT}
      - TRACE_TYPE=${TRACE_TYPE}
      - SERVICE_NAME=${SERVICE_NAME}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
    restart: always
    ports:
      - 3001:3001
    networks:
      - api-postgres
  
networks:
  api-postgres:
    driver: bridge

volumes:
  postgres_local_data: {}