apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: logistic-service
serialPipeline:
  stages:
    - targetId: dev-target
      profiles: [dev]
    - targetId: prod-target
      profiles: [prod]
      strategy:
        standard:
          predeploy:
            actions: ["re-tag-push-prod"]