options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE 

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'print-info'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Build: $BUILD_ID | TAG: $SHORT_SHA | Branch: $BRANCH_NAME"    

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
      - './'
    timeout: '1200s'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args: ['push', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest']
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-sha'
    args: ['push', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA']
    waitFor: ['build-image']